# Generated by Django 4.1.3 on 2022-11-25 02:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import supervision.schemas
import user.validators
import utils.schemas


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SuperVision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "datasources_configs",
                    models.JSONField(
                        default=list,
                        validators=[
                            utils.schemas.SchemaValidator(
                                supervision.schemas.SupervisionDatasourcesConfig
                            )
                        ],
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supervisors",
                        to=settings.AUTH_USER_MODEL,
                        validators=[
                            user.validators.UserRoleValidator("patient")
                        ],
                    ),
                ),
                (
                    "supervisor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supervisees",
                        to=settings.AUTH_USER_MODEL,
                        validators=[
                            user.validators.UserRoleValidator("supervisor")
                        ],
                    ),
                ),
            ],
            options={
                "unique_together": {("supervisor", "patient")},
            },
        ),
    ]
