# Generated by Django 4.1.3 on 2022-11-27 15:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import user.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Supervision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supervisors",
                        to=settings.AUTH_USER_MODEL,
                        validators=[
                            user.validators.UserRoleValidator("patient")
                        ],
                    ),
                ),
                (
                    "supervisor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supervisees",
                        to=settings.AUTH_USER_MODEL,
                        validators=[
                            user.validators.UserRoleValidator("supervisor")
                        ],
                    ),
                ),
            ],
            options={
                "unique_together": {("supervisor", "patient")},
            },
        ),
        migrations.CreateModel(
            name="DatasourcesConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "datasource",
                    models.CharField(
                        choices=[("heart_rate", "Heart Rate")], max_length=127
                    ),
                ),
                (
                    "supervision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="datasources_configs",
                        to="supervision.supervision",
                    ),
                ),
            ],
            options={
                "unique_together": {("supervision", "datasource")},
            },
        ),
    ]
