# Generated by Django 4.1.3 on 2022-11-27 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supervision", "0002_datasourcesconfig_alerting_medium"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datasourcesconfig",
            name="alerting_medium",
            field=models.CharField(
                choices=[("off", "Off"), ("sms", "Sms"), ("email", "Email")],
                default="off",
                help_text="Alerting medium for this datasource",
                max_length=31,
            ),
        ),
    ]
