# Generated by Django 4.1.3 on 2022-11-27 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supervision", "0003_alter_datasourcesconfig_alerting_medium"),
    ]

    operations = [
        migrations.AddField(
            model_name="datasourcesconfig",
            name="alerting_criteria",
            field=models.CharField(
                blank=True,
                help_text="Alerting criteria for this datasource",
                max_length=255,
            ),
        ),
    ]
