# Generated by Django 4.1.3 on 2023-02-06 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supervision", "0005_alter_datasourcesconfig_alerting_criteria"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datasourcesconfig",
            name="alerting_criteria",
            field=models.CharField(
                blank=True,
                default="0",
                help_text='Alerting criteria for this datasource. Supported variables: "hr" for "heart rate", "sbp" for "systolic bp", "dbp" for "diastolic bp"',
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="datasourcesconfig",
            name="datasource",
            field=models.CharField(
                choices=[
                    ("heart_rate", "Heart Rate"),
                    ("blood_pressure", "Blood Pressure"),
                ],
                max_length=127,
            ),
        ),
    ]
