# Generated by Django 4.1.3 on 2022-11-28 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import user.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("device", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="last_used_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="device",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="devices",
                to=settings.AUTH_USER_MODEL,
                validators=[user.validators.UserRoleValidator("patient")],
            ),
        ),
    ]
