# Generated by Django 4.1.3 on 2022-11-27 17:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                blank=True,
                max_length=31,
                validators=[
                    django.core.validators.RegexValidator(
                        regex="^\\+?[0-9]{10,15}$"
                    )
                ],
            ),
        ),
    ]
