# Generated by Django 4.1.3 on 2022-11-28 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0001_initial"),
        ("datasource", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="heartratedata",
            name="device",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="heart_rate_data",
                to="device.device",
            ),
        ),
    ]
