# Generated by Django 4.1.3 on 2023-02-06 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import user.validators


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0002_device_last_used_at_alter_device_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "datasource",
            "0003_alter_heartratedata_device_alter_heartratedata_user",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="BloodPressureData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("record_time", models.DateTimeField()),
                ("systolic_bp", models.IntegerField()),
                ("diastolic_bp", models.IntegerField()),
                (
                    "device",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="device.device",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        validators=[
                            user.validators.UserRoleValidator("patient")
                        ],
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
